# Site settings
title: Freelancer
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
copyright: Dr. Henry Jekyll

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
defaults:
  -
    scope:
      path: ""
    values:
      icon: "star"
  -
    scope:
      path: ""
      type: "homepage"
    values:
      theme: "primary"
  -
    scope:
      path: ""
      type: "footer"
    values:
      colsize: "col-md-4"

collections:
  - homepage
  - footer

gems: [jekyll-assets]

sass:
    sass_dir: _sass
    style: compressed

assets:
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/stylesheets    

markdown: kramdown
permalink: pretty
